<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_paymentInfo</name>
   <tag></tag>
   <elementGuidId>ae2f7035-1a28-40cf-83e3-d7f0fe182603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkout_summary_container&quot;]/div/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkout_summary_container&quot;]/div/div[2]/div[1]</value>
      <webElementGuid>c110a92c-ca2c-4063-889d-2864371aa5f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
