<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_priceTotal</name>
   <tag></tag>
   <elementGuidId>2a6c4f25-46d8-48a9-bba2-b911be3d95eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkout_summary_container&quot;]/div/div[2]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkout_summary_container&quot;]/div/div[2]/div[5]</value>
      <webElementGuid>0b690e4b-9699-4d09-9d97-b17c1a847606</webElementGuid>
   </webElementProperties>
</WebElementEntity>
